"""esquema inicial persistencia

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-11 13:42:44.546489
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('accion', sa.String(length=64), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=32), nullable=True),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_id', sa.String(length=48), nullable=True),
    sa.Column('control_id', sa.String(length=48), nullable=True),
    sa.Column('resultado', sa.String(length=48), nullable=True),
    sa.Column('estado_anterior', sa.String(length=48), nullable=True),
    sa.Column('estado_posterior', sa.String(length=48), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_auditoria_run_seq')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_run_id'), ['run_id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_interno', sa.String(length=48), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('tipo_documental', sa.String(length=40), nullable=False),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('estado_procesamiento', sa.String(length=40), nullable=False),
    sa.Column('ubicacion_segura', sa.String(length=512), nullable=True),
    sa.Column('cantidad_paginas', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('documentai_raw_ref', sa.String(length=512), nullable=True),
    sa.Column('documentai_processor_version', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado_procesamiento IN ('anticipo_pagado_sin_factura_final', 'anticipo_pendiente_factura_final', 'anticipo_retenido_sin_aprobacion', 'aprobado', 'bloqueada', 'cerrada', 'controles_en_ejecucion', 'domiciliacion_pendiente_conciliacion', 'en_cola', 'en_cuarentena', 'en_lote', 'extraido', 'fallido', 'liberada_al_banco', 'lote_devuelto', 'otro_documento_revisar', 'pendiente_datos_internos', 'preparado_para_pago', 'procesando', 'proximo_ciclo', 'recibido', 'requiere_revision', 'retenido_alta_proveedor', 'tarjeta_pendiente_conciliacion', 'validando')", name='ck_documento_estado'),
    sa.CheckConstraint("tipo_documental IN ('invoice', 'proforma_or_advance_request', 'other', 'oc')", name='ck_documento_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_hash_archivo'), ['hash_archivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_id_interno'), ['id_interno'], unique=True)

    op.create_table('lotes_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_lote', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sign_off_a', sa.JSON(), nullable=True),
    sa.Column('sign_off_b', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado IN ('propuesto', 'revalidado_a', 'pendiente_aprobacion_humana', 'aprobado', 'liberado_al_banco', 'rechazado', 'detenido_por_checker')", name='ck_lote_estado'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_pago_fecha_lote'), ['fecha_lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_pago_run_id'), ['run_id'], unique=False)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=32), nullable=False),
    sa.Column('nombre_legal', sa.String(length=255), nullable=True),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('codigo_pais', sa.String(length=2), nullable=False),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('intercompany', sa.Boolean(), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('razon_social_confirmada', sa.Boolean(), nullable=False),
    sa.Column('iban_autorizado', sa.String(length=40), nullable=True),
    sa.Column('banco_autorizado', sa.String(length=128), nullable=True),
    sa.Column('sepa_mandate_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'retenido', 'baja')", name='ck_proveedor_estado'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_codigo_interno'), ['codigo_interno'], unique=True)

    op.create_table('aprobaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('aprobador', sa.String(length=128), nullable=False),
    sa.Column('nivel_requerido', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('evidencia_gate', sa.JSON(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('aprobar', 'rechazar')", name='ck_aprobacion_decision'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aprobaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aprobaciones_lote_id'), ['lote_id'], unique=False)

    op.create_table('controles_ejecutados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=48), nullable=False),
    sa.Column('version_control', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('resultado', sa.String(length=24), nullable=False),
    sa.Column('severidad', sa.String(length=8), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('checker', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controles_ejecutados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controles_ejecutados_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_controles_ejecutados_documento_id'), ['documento_id'], unique=False)

    op.create_table('excepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=48), nullable=False),
    sa.Column('severidad', sa.String(length=8), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('fraud_alert', sa.Boolean(), nullable=False),
    sa.Column('estado_resolucion', sa.String(length=16), nullable=False),
    sa.Column('usuario_responsable', sa.String(length=128), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado_resolucion IN ('abierta', 'en_revision', 'resuelta', 'descartada')", name='ck_excepcion_estado'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excepciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excepciones_documento_id'), ['documento_id'], unique=False)

    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('comprador', sa.String(length=128), nullable=True),
    sa.Column('numero_factura', sa.String(length=64), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('importe_neto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('importe_impuestos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('importe_descuentos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('importe_gastos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('importe_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('importe_pendiente', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('condicion_pago', sa.String(length=128), nullable=True),
    sa.Column('referencia_proyecto', sa.String(length=48), nullable=True),
    sa.Column('referencia_contrato', sa.String(length=48), nullable=True),
    sa.Column('referencia_orden', sa.String(length=48), nullable=True),
    sa.Column('ruta_ap', sa.String(length=24), nullable=False),
    sa.Column('metodo_pago', sa.String(length=32), nullable=False),
    sa.Column('tratamiento_iva', sa.String(length=48), nullable=False),
    sa.Column('nivel_confianza', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('estado_operativo', sa.String(length=40), nullable=True),
    sa.Column('iban_en_factura', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ruta_ap IN ('po', 'non_po', 'anticipo', 'otro')", name='ck_factura_ruta'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_documento_id'), ['documento_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_facturas_estado_operativo'), ['estado_operativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index('uq_factura_activa', ['proveedor_id', 'numero_factura'], unique=True, sqlite_where=sa.text("numero_factura IS NOT NULL AND (estado_operativo IS NULL OR estado_operativo <> 'bloqueada')"), postgresql_where=sa.text("numero_factura IS NOT NULL AND (estado_operativo IS NULL OR estado_operativo <> 'bloqueada')"))

    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oc', sa.String(length=48), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=128), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('importe_autorizado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('gl_account', sa.String(length=16), nullable=True),
    sa.Column('mgmt_category', sa.String(length=64), nullable=True),
    sa.Column('project_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado IN ('aprobada', 'borrador', 'cerrada')", name='ck_oc_estado'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_numero_oc'), ['numero_oc'], unique=True)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('proveedor_cambios_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('iban_anterior', sa.String(length=40), nullable=True),
    sa.Column('iban_nuevo', sa.String(length=40), nullable=True),
    sa.Column('banco_anterior', sa.String(length=128), nullable=True),
    sa.Column('banco_nuevo', sa.String(length=128), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('cambiado_por', sa.String(length=128), nullable=True),
    sa.Column('aprobado_por_1', sa.String(length=128), nullable=True),
    sa.Column('aprobado_por_2', sa.String(length=128), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedor_cambios_bancarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_cambios_bancarios_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('revision_humana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('campo_original', sa.String(length=64), nullable=True),
    sa.Column('valor_extraido', sa.Text(), nullable=True),
    sa.Column('valor_corregido', sa.Text(), nullable=True),
    sa.Column('motivo_correccion', sa.Text(), nullable=True),
    sa.Column('revisor', sa.String(length=128), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_humana', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_humana_documento_id'), ['documento_id'], unique=False)

    op.create_table('lote_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', name='uq_factura_un_solo_lote')
    )
    with op.batch_alter_table('lote_facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lote_facturas_lote_id'), ['lote_id'], unique=False)

    op.create_table('oc_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id', 'line_id', name='uq_oc_linea')
    )
    with op.batch_alter_table('oc_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oc_lineas_orden_id'), ['orden_id'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('estado_pago', sa.String(length=24), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('referencia_externa', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado_pago IN ('preparado', 'liberado', 'conciliado', 'rechazado')", name='ck_pago_estado'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_lote_id'), ['lote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_lote_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_factura_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('oc_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oc_lineas_orden_id'))

    op.drop_table('oc_lineas')
    with op.batch_alter_table('lote_facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lote_facturas_lote_id'))

    op.drop_table('lote_facturas')
    with op.batch_alter_table('revision_humana', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_humana_documento_id'))

    op.drop_table('revision_humana')
    with op.batch_alter_table('proveedor_cambios_bancarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedor_cambios_bancarios_proveedor_id'))

    op.drop_table('proveedor_cambios_bancarios')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_numero_oc'))

    op.drop_table('ordenes_compra')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index('uq_factura_activa', sqlite_where=sa.text("numero_factura IS NOT NULL AND (estado_operativo IS NULL OR estado_operativo <> 'bloqueada')"), postgresql_where=sa.text("numero_factura IS NOT NULL AND (estado_operativo IS NULL OR estado_operativo <> 'bloqueada')"))
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_estado_operativo'))
        batch_op.drop_index(batch_op.f('ix_facturas_documento_id'))

    op.drop_table('facturas')
    with op.batch_alter_table('excepciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excepciones_documento_id'))

    op.drop_table('excepciones')
    with op.batch_alter_table('controles_ejecutados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controles_ejecutados_documento_id'))
        batch_op.drop_index(batch_op.f('ix_controles_ejecutados_correlation_id'))

    op.drop_table('controles_ejecutados')
    with op.batch_alter_table('aprobaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aprobaciones_lote_id'))

    op.drop_table('aprobaciones')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_codigo_interno'))

    op.drop_table('proveedores')
    with op.batch_alter_table('lotes_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_pago_run_id'))
        batch_op.drop_index(batch_op.f('ix_lotes_pago_fecha_lote'))

    op.drop_table('lotes_pago')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_id_interno'))
        batch_op.drop_index(batch_op.f('ix_documentos_hash_archivo'))
        batch_op.drop_index(batch_op.f('ix_documentos_correlation_id'))

    op.drop_table('documentos')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_run_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_correlation_id'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
