"""add lifecycle phase

Revision ID: 0002_lifecycle
Revises: 0001_initial
Create Date: 2026-07-11 13:43:30.015972
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_lifecycle'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase_ciclo_vida', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_documentos_fase_ciclo_vida'), ['fase_ciclo_vida'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_fase_ciclo_vida'))
        batch_op.drop_column('fase_ciclo_vida')

    # ### end Alembic commands ###
